//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DescendantEntry) DeepCopyInto(out *DescendantEntry) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DescendantEntry.
func (in *DescendantEntry) DeepCopy() *DescendantEntry {
	if in == nil {
		return nil
	}
	out := new(DescendantEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftAffectedCRRef) DeepCopyInto(out *DriftAffectedCRRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftAffectedCRRef.
func (in *DriftAffectedCRRef) DeepCopy() *DriftAffectedCRRef {
	if in == nil {
		return nil
	}
	out := new(DriftAffectedCRRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftSignal) DeepCopyInto(out *DriftSignal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftSignal.
func (in *DriftSignal) DeepCopy() *DriftSignal {
	if in == nil {
		return nil
	}
	out := new(DriftSignal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriftSignal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftSignalList) DeepCopyInto(out *DriftSignalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DriftSignal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftSignalList.
func (in *DriftSignalList) DeepCopy() *DriftSignalList {
	if in == nil {
		return nil
	}
	out := new(DriftSignalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DriftSignalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftSignalSpec) DeepCopyInto(out *DriftSignalSpec) {
	*out = *in
	in.ObservedAt.DeepCopyInto(&out.ObservedAt)
	out.AffectedCRRef = in.AffectedCRRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftSignalSpec.
func (in *DriftSignalSpec) DeepCopy() *DriftSignalSpec {
	if in == nil {
		return nil
	}
	out := new(DriftSignalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DriftSignalStatus) DeepCopyInto(out *DriftSignalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DriftSignalStatus.
func (in *DriftSignalStatus) DeepCopy() *DriftSignalStatus {
	if in == nil {
		return nil
	}
	out := new(DriftSignalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageRecord) DeepCopyInto(out *LineageRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageRecord.
func (in *LineageRecord) DeepCopy() *LineageRecord {
	if in == nil {
		return nil
	}
	out := new(LineageRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LineageRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageRecordList) DeepCopyInto(out *LineageRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LineageRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageRecordList.
func (in *LineageRecordList) DeepCopy() *LineageRecordList {
	if in == nil {
		return nil
	}
	out := new(LineageRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LineageRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageRecordRootBinding) DeepCopyInto(out *LineageRecordRootBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageRecordRootBinding.
func (in *LineageRecordRootBinding) DeepCopy() *LineageRecordRootBinding {
	if in == nil {
		return nil
	}
	out := new(LineageRecordRootBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageRecordSpec) DeepCopyInto(out *LineageRecordSpec) {
	*out = *in
	out.RootBinding = in.RootBinding
	if in.DescendantRegistry != nil {
		in, out := &in.DescendantRegistry, &out.DescendantRegistry
		*out = make([]DescendantEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyBindingStatus != nil {
		in, out := &in.PolicyBindingStatus, &out.PolicyBindingStatus
		*out = new(InfrastructurePolicyBindingStatus)
		**out = **in
	}
	if in.OutcomeRegistry != nil {
		in, out := &in.OutcomeRegistry, &out.OutcomeRegistry
		*out = make([]OutcomeEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RetentionPolicy != nil {
		in, out := &in.RetentionPolicy, &out.RetentionPolicy
		*out = new(LineageRetentionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageRecordSpec.
func (in *LineageRecordSpec) DeepCopy() *LineageRecordSpec {
	if in == nil {
		return nil
	}
	out := new(LineageRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageRecordStatus) DeepCopyInto(out *LineageRecordStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageRecordStatus.
func (in *LineageRecordStatus) DeepCopy() *LineageRecordStatus {
	if in == nil {
		return nil
	}
	out := new(LineageRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfrastructurePolicyBindingStatus) DeepCopyInto(out *InfrastructurePolicyBindingStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfrastructurePolicyBindingStatus.
func (in *InfrastructurePolicyBindingStatus) DeepCopy() *InfrastructurePolicyBindingStatus {
	if in == nil {
		return nil
	}
	out := new(InfrastructurePolicyBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerConfig) DeepCopyInto(out *RunnerConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerConfig.
func (in *RunnerConfig) DeepCopy() *RunnerConfig {
	if in == nil {
		return nil
	}
	out := new(RunnerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerConfigList) DeepCopyInto(out *RunnerConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RunnerConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerConfigList.
func (in *RunnerConfigList) DeepCopy() *RunnerConfigList {
	if in == nil {
		return nil
	}
	out := new(RunnerConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RunnerConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerConfigSpec) DeepCopyInto(out *RunnerConfigSpec) {
	*out = *in
	if in.Phases != nil {
		in, out := &in.Phases, &out.Phases
		*out = make([]RunnerPhaseConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]RunnerConfigStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OperationalHistory != nil {
		in, out := &in.OperationalHistory, &out.OperationalHistory
		*out = make([]RunnerOperationalHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaintenanceTargetNodes != nil {
		in, out := &in.MaintenanceTargetNodes, &out.MaintenanceTargetNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerConfigSpec.
func (in *RunnerConfigSpec) DeepCopy() *RunnerConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RunnerConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerConfigStatus) DeepCopyInto(out *RunnerConfigStatus) {
	*out = *in
	if in.Capabilities != nil {
		in, out := &in.Capabilities, &out.Capabilities
		*out = make([]RunnerCapabilityEntry, len(*in))
		copy(*out, *in)
	}
	if in.StepResults != nil {
		in, out := &in.StepResults, &out.StepResults
		*out = make([]RunnerConfigStepResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerConfigStatus.
func (in *RunnerConfigStatus) DeepCopy() *RunnerConfigStatus {
	if in == nil {
		return nil
	}
	out := new(RunnerConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineageRetentionPolicy) DeepCopyInto(out *LineageRetentionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineageRetentionPolicy.
func (in *LineageRetentionPolicy) DeepCopy() *LineageRetentionPolicy {
	if in == nil {
		return nil
	}
	out := new(LineageRetentionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutcomeEntry) DeepCopyInto(out *OutcomeEntry) {
	*out = *in
	in.OutcomeTimestamp.DeepCopyInto(&out.OutcomeTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutcomeEntry.
func (in *OutcomeEntry) DeepCopy() *OutcomeEntry {
	if in == nil {
		return nil
	}
	out := new(OutcomeEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerCapabilityEntry) DeepCopyInto(out *RunnerCapabilityEntry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerCapabilityEntry.
func (in *RunnerCapabilityEntry) DeepCopy() *RunnerCapabilityEntry {
	if in == nil {
		return nil
	}
	out := new(RunnerCapabilityEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerConfigStep) DeepCopyInto(out *RunnerConfigStep) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerConfigStep.
func (in *RunnerConfigStep) DeepCopy() *RunnerConfigStep {
	if in == nil {
		return nil
	}
	out := new(RunnerConfigStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerConfigStepResult) DeepCopyInto(out *RunnerConfigStepResult) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerConfigStepResult.
func (in *RunnerConfigStepResult) DeepCopy() *RunnerConfigStepResult {
	if in == nil {
		return nil
	}
	out := new(RunnerConfigStepResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerOperationalHistoryEntry) DeepCopyInto(out *RunnerOperationalHistoryEntry) {
	*out = *in
	in.AppliedAt.DeepCopyInto(&out.AppliedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerOperationalHistoryEntry.
func (in *RunnerOperationalHistoryEntry) DeepCopy() *RunnerOperationalHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(RunnerOperationalHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RunnerPhaseConfig) DeepCopyInto(out *RunnerPhaseConfig) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RunnerPhaseConfig.
func (in *RunnerPhaseConfig) DeepCopy() *RunnerPhaseConfig {
	if in == nil {
		return nil
	}
	out := new(RunnerPhaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembership) DeepCopyInto(out *SeamMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembership.
func (in *SeamMembership) DeepCopy() *SeamMembership {
	if in == nil {
		return nil
	}
	out := new(SeamMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembershipList) DeepCopyInto(out *SeamMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SeamMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembershipList.
func (in *SeamMembershipList) DeepCopy() *SeamMembershipList {
	if in == nil {
		return nil
	}
	out := new(SeamMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SeamMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembershipSpec) DeepCopyInto(out *SeamMembershipSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembershipSpec.
func (in *SeamMembershipSpec) DeepCopy() *SeamMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(SeamMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeamMembershipStatus) DeepCopyInto(out *SeamMembershipStatus) {
	*out = *in
	if in.AdmittedAt != nil {
		in, out := &in.AdmittedAt, &out.AdmittedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeamMembershipStatus.
func (in *SeamMembershipStatus) DeepCopy() *SeamMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(SeamMembershipStatus)
	in.DeepCopyInto(out)
	return out
}

